support meta tags in unexpected key messages
dry-rb/dry-schema pull request #313
Opened 2020-09-03 13:47 UTC by tadeusz-niemiec

Fixes #310

2020-09-04 07:38 UTC, solnic requested changes
Thanks for taking care of this. There's just one small issue to address before I can merge this in. Please also rebase after applying the suggestion! 🙇

2020-09-04 07:38 UTC, solnic commented on lib/dry/schema/message_compiler.rb
> +          meta: msg[:meta] || {},
```suggestion
          meta: msg[:meta] || EMPTY_HASH,
```

This way we won't be allocating extra hash. Message objects are "immutable" so this is perfectly fine.

2020-09-04 08:50 UTC, tadeusz-niemiec commented
> Thanks for taking care of this. There's just one small issue to address before I can merge this in. Please also rebase after applying the suggestion!

Done :)

2020-09-07 08:13 UTC, solnic approved these changes
👏 👏 👏 🙇

2020-09-07 08:14 UTC, merged