Fix types and key maps for composed schemas
dry-rb/dry-schema pull request #415
Opened 2022-07-06 23:19 UTC by robhanlon22

Two issues addressed here:
* The DSL types hash did not merge in parent types. Override the types
  accessors with one that merges in parent types.
* Operation processing within Macros::Schema did not recursively merge
  any nested operations.

These fixes allow for different key sets to be processed correctly.

2022-07-06 23:19 UTC, robhanlon22 commented
@solnic looks like there is an issue when running the tests against dry-types's current `main` branch.

2022-07-26 04:55 UTC, solnic commented
@robhanlon22 please rebase, main is now fixed

2022-08-08 21:40 UTC, robhanlon22 commented
@solnic this is ready for eyeballs finally! sorry, had a bunch of other stuff i needed to get to

2022-08-10 07:57 UTC, solnic requested changes
A couple of smaller things to address but overall 😱 👏🏻 🙇🏻

2022-08-10 07:57 UTC, solnic commented on spec/integration/type_inheritance_spec.rb
> +        required(:foo).filled(:hash?)
```suggestion
        required(:foo).filled(:hash)
```

2022-08-10 07:57 UTC, solnic commented on spec/integration/type_inheritance_spec.rb
> +                required(:wow).filled(eql?: "c")
```suggestion
                required(:wow).filled(:string, eql?: "c")
```

2022-08-10 07:57 UTC, solnic commented on spec/integration/type_inheritance_spec.rb
> +                required(:such).filled(eql?: "cool")
```suggestion
                required(:such).filled(:string, eql?: "cool")
```

2022-08-10 07:57 UTC, solnic commented on spec/spec_helper.rb
> +# Warning.process { |w| raise w }
Could this be restored?

2022-08-10 16:50 UTC, robhanlon22 commented
Comments addressed!

2022-08-12 08:08 UTC, solnic approved these changes

2022-08-12 08:08 UTC, merged