Make the yaml cache fully thread-safe
dry-rb/dry-schema pull request #440
Opened 2022-11-20 18:53 UTC by mensfeld

```
Concurrent::Map.new { |h, k| h[k] = Concurrent::Map.new }
```

is prone to a race condition, thus the cache won't be fully thread safe if definitions are parsed in multiple threads.

This PR fixes that.

Ref: https://github.com/ruby-concurrency/concurrent-ruby/issues/970

2022-11-20 18:55 UTC, solnic requested changes

2022-11-20 18:55 UTC, solnic commented on lib/dry/schema/messages/yaml.rb
> +          p key
I guess this should be removed

2022-11-22 09:26 UTC, mensfeld commented
specs dont seem to be related to this change

2022-11-23 05:53 UTC, solnic requested changes
I'm afraid spec failures are indeed caused by the fix, seems like cache isn't cleared properly between spec runs now.

2022-11-23 06:00 UTC, mensfeld commented
Got it. WIll look at this today.

2022-11-23 08:06 UTC, flash-gordon commented
main is green, merging

2022-11-23 08:06 UTC, merged

2022-11-24 21:56 UTC, granthusbands commented
@mensfeld  You missed the `||=` that you've fixed in pull requests for other projects.

2022-11-25 11:24 UTC, mensfeld commented
@granthusbands I did not miss it. I explicitly do not do it here to make the change small. I pointed out in the article that I wanted to keep the scope small because I do not know how given libs operate.

>  that you've fixed in pull requests for other projects.

Not exactly the same. In most cases, I fixed the internal `||=`, not the external. Nonetheless you are right and feel free to create a PR :) @solnic should be happy